'use strict';

module.exports = Object.freeze({
    SEARCH_START: 'SEARCH_START',
    SEARCH_RESULTS: 'SEARCH_RESULTS',
    SEARCH_ERROR: 'SEARCH_ERROR',
    SEARCH_SINGLE_RESULTS: 'SEARCH_SINGLE_RESULTS',
    SEARCH_SINGLE_ERROR: 'SEARCH_SINGLE_ERROR',
    LIST_RESULTS: 'LIST_RESULTS',
    LIST_ERROR: 'LIST_ERROR'
});
